### ISSUE TITLE
android not running 

### ISSUE THREAD

**Issue by blackpink7** [JivoChat/JivoSDK-FlutterDemo#3]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.chrisbanes:PhotoView:2.3.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/chrisbanes/PhotoView/2.3.0/PhotoView-2.3.0.pom
       - https://repo.maven.apache.org/maven2/com/github/chrisbanes/PhotoView/2.3.0/PhotoView-2.3.0.pom
       - https://storage.googleapis.com/download.flutter.io/com/github/chrisbanes/PhotoView/2.3.0/PhotoView-2.3.0.pom
     Required by:
         project :app > project :jivosdk_plugin > com.jivosite.sdk:android-sdk:2.2.2

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 27s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by tavtorkin-jivo** [comment]
@blackpink7 Hi! Do you have access to https://www.jitpack.io?
Сan you show the **android/build.gradle** settings?
